[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false
chaos-engine = true
secure-mode = true
post-quantum = true

[programs.devnet]
glitch_gremlin_governance = "CGdnYbXRM3trAKUeSiPT4it9obeo1iTx3BJhgfriADSL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "config/1fnZqqDYRaq7SGqDJ5rWZM2dJjGpaHfrdDDssV1ggai.json"

[workspace]
members = ["programs/governance"]
types = "target/types"

[workspace.metadata.anchor]
program-type = "sbf"
target = "sbf-solana-solana"
sbf-sdk = "/root/agave/platform-tools-sdk/sbf"
features = ["secure-mode", "chaos-engine", "post-quantum"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[chaos-engine]
enabled = true
resilience-level = "maximum"
quantum-resistant = true
ai-integration = true
memory-protection = true
zero-knowledge = true
secure-inference = true
attack-simulation = true
fault-injection = true
entropy-source = "hardware"

[metrics]
enabled = true
prometheus = true
opentelemetry = true
tracing = true
dashboard = true
