[toolchain]
channel = "2024"
components = ["rust-src", "rustc-dev", "llvm-tools-preview", "solana-sbf"]
profile = "minimal"
anchor_version = "0.29.0"
solana_version = "1.18.11"

[features]
resolution = true
skip-lint = false
chaos-engine = true
secure-mode = true
post-quantum = true

[programs.devnet]
glitch_gremlin_governance = "CGdnYbXRM3trAKUeSiPT4it9obeo1iTx3BJhgfriADSL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "config/1fnZqqDYRaq7SGqDJ5rWZM2dJjGpaHfrdDDssV1ggai.json"

[workspace]
members = ["programs/governance"]
types = "target/types"

[workspace.metadata.anchor]
program-type = "sbf"
target = "sbf-solana-solana"
sbf-sdk = "/root/agave/platform-tools-sdk/sbf"
sbf-tools-version = "1.17.6"
features = ["secure-mode", "chaos-engine", "post-quantum"]
build-flags = ["--features", "chaos-engine,post-quantum"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[build]
target = "sbf-solana-solana"
rustflags = [
    "-C", "link-arg=--soname=libchaos_engine_v3.so",
    "-C", "opt-level=3",
    "-C", "panic=abort", 
    "-C", "debug-assertions=no",
    "-C", "overflow-checks=no",
    "-C", "embed-bitcode=yes",
    "-C", "strip=symbols",
    "-C", "target-feature=+solana-sbf,+solana-smartheap",
    "-C", "target-cpu=solana-sbfv2",
    "-C", "llvm-args=--x86-asm-syntax=intel --vectorize-loops --unroll-threshold=4",
    "-C", "inline-threshold=100",
    "-C", "no-redzone=yes",
    "-C", "embed-llvm-bitcode=yes",
    "-Z", "mir-opt-level=5",
    "-Z", "instrument-coverage",
    "-Z", "build-std=core,alloc,panic_abort",
    "-Z", "build-std-features=compiler-builtins-mem",
    "-Z", "unleash-the-mango"
]

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[verify]
enabled = true
checksum = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
whitelist = [
    "solana-program@1.17.6",
    "anchor-lang@0.29.0",
    "chaos-engine-proto@3.14"
]

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[chaos-engine]
enabled = true
resilience-level = "maximum"
quantum-resistant = true
ai-integration = true
memory-protection = true
zero-knowledge = true
secure-inference = true
attack-simulation = true
fault-injection = true
entropy-source = "hardware"

[metrics]
enabled = true
prometheus = true
opentelemetry = true
tracing = true
dashboard = true
