[workspace]
resolver = "2"
members = [
    "src/token/program",
    "src/token/worker", 
    "src/token/shared",
    "src/token/governance-worker"
]
exclude = [
    "deps/solana-sdk"
]

[workspace.dependencies]
solana-program = { version = "1.18.26", default-features = false, features = ["program"] }
solana-sdk = { version = "1.18.26", default-features = false }
solana-program-test = "1.18.26"
mongodb = { version = "2.8", features = ["tokio-runtime"], default-features = false }
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1.0", features = ["full"] }
bson = "2.13.0"
serde_json = "1.0.137"
serde = { version = "1.0", features = ["derive"] }
borsh = "0.10.3"

# Linux-specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.2.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
