[workspace]
resolver = "2"
members = [
    "src/token/program",
    "src/token/worker",
    "src/token/shared"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
borsh = { version = "0.10", features = ["derive"] }
solana-program = "1.18.26"
spl-token = { version = "3.2.0" }
chrono = "0.4"
redis = "0.23.0"
solana-client = "1.18.26"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
lazy_static = "1.4.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
