[workspace]
resolver = "2"
members = [
    "src/token/program"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
borsh = { version = "0.10", features = ["derive"] }
solana-program = "1.18.26"
spl-token = { version = "3.2.0" }
chrono = "0.4"
