[workspace]
resolver = "2"
members = [
    "src/token/program",
    "src/token/worker", 
    "src/token/shared",
    "src/token/governance-worker"
]
exclude = [
    "deps/solana-sdk"
]

[workspace.dependencies]
solana-sdk = "1.17"
mongodb = { version = "2.8", features = ["tokio-runtime"] }
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1.0", features = ["full"] }
bson = "2.13.0"
serde_json = "1.0.137"
serde = { version = "1.0", features = ["derive"] }
raw-cpuid = { version = "10.6", features = ["aarch64"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
