[workspace]
resolver = "2"
members = [
    "src/token/program",
    "src/token/worker", 
    "src/token/shared",
    "src/token/governance-worker"
]

[workspace.dependencies]
borsh = "0.10.3"
borsh-derive = "0.10.3"
solana-program = "1.18.26"
spl-token = { version = "3.2.0" }
chrono = "0.4"
redis = "0.23.0"
solana-client = "1.18.26"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
lazy_static = "1.4.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
bytemuck = "=1.4.0"
bytemuck_derive = "=1.4.0"
