[workspace]
resolver = "1"
members = [
    "src/token/program",
    "src/token/worker", 
    "src/token/shared",
    "src/token/governance-worker"
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
