[workspace]
resolver = "2"
members = [
    "programs/*"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[profile.dev]
overflow-checks = true

[workspace.dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.18"
solana-program-test = "1.18"
solana-sdk = "1.18"
solana-account-decoder = "1.18"
solana-client = "1.18"
solana-transaction-status = "1.18"
solana-banks-interface = "1.18"
solana-banks-client = "1.18"
solana-runtime = "1.18"
bs58 = "0.5.0"
