[workspace]
resolver = "2"
members = [
    "src/token/program",
    "src/token/worker", 
    "src/token/shared",
    "src/token/governance-worker"
]

[workspace.dependencies]
solana-sdk = { path = "deps/solana-sdk" }
mongodb = { version = "3.2", features = ["tokio-runtime"] }
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1.0", features = ["full"] }
bson = "2.13.0"
serde_json = "1.0.137"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
