[package]
name = "glitch-gremlin-governance"
version = "0.1.0"
description = "On-chain governance for Glitch Gremlin AI protocol"
edition = "2021"

[dependencies]
# Web server dependencies
axum = { version = "0.7.5", features = ["http1", "http2", "macros"] }
hyper = { version = "0.14.27", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs"] }

anchor-lang = { version = "0.30.1", features = ["derive"] }
anchor-spl = "0.30.1"
borsh = "0.10"
borsh-derive = "0.10"
redis = { version = "0.23", features = ["tokio-comp"] }
solana-program = "1.16.5"
thiserror = "1.0"
arrayref = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"], default-features = false }
mongodb = { version = "2.8.2", default-features = false, features = ["tokio-sync"] }
futures = "0.3.30"
serde_json = "1.0"

[features]
default = ["custom-heap", "custom-panic"]
custom-heap = []
custom-panic = []

[profile.dev]
panic = "unwind"
overflow-checks = true

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
