[workspace]
resolver = "2"
members = [
    "src/token/program",
    "src/token/worker", 
    "src/token/shared",
    "src/token/governance-worker"
]
exclude = [
    "deps/solana-sdk"
]

[workspace.dependencies]
solana-program = "1.18.26"
solana-sdk = "1.18.26"
solana-program-test = "1.18.26"
mongodb = { version = "2.8", features = ["tokio-runtime"], default-features = false }
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1.0", features = ["full"] }
bson = "2.13.0"
serde_json = "1.0.137"
serde = { version = "1.0", features = ["derive"] }
borsh = "0.10.3"

# Platform specific features
[workspace.package.metadata]
default-features = []
features = ["linux"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
