[package]
name = "glitch-gremlin-governance"
version = "0.1.0"
description = "On-chain governance for Glitch Gremlin AI protocol"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.30.1", features = ["derive"] }
anchor-spl = "0.30.1"
borsh = "0.10"
borsh-derive = "0.10"
redis = { version = "0.23", features = ["tokio-comp"] }
solana-program = "1.16.5"
thiserror = "1.0"
arrayref = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
mongodb = { version = "2.6", default-features = false }
serde_json = "1.0"

[features]
default = ["anchor-debug"]
anchor-debug = []

[profile.dev]
panic = "unwind"
overflow-checks = true

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
