[toolchain]
channel = "nightly-2023-05-31"  # Version known to work with Solana BPF
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "rust-std"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "bpfel-unknown-unknown"
]
profile = "minimal"
