[toolchain]
channel = "nightly-2023-12-10"  # Last verified working version with BPF components
components = ["rustfmt", "clippy", "llvm-tools-preview", "rust-src", "rust-std"]
targets = ["x86_64-unknown-linux-gnu", "bpfel-unknown-unknown", "bpfeb-unknown-unknown"]
