[toolchain]
channel = "nightly-2023-05-30"  # Version with bpfel-unknown-unknown rust-std support
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "rust-std"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "bpfel-unknown-unknown"
]
profile = "minimal"
