[toolchain]
channel = "nightly-2025-01-31"  # Updated to latest verified working version with BPF components
components = ["rustfmt", "clippy", "llvm-tools-preview", "rust-src", "rust-std"]
targets = ["x86_64-unknown-linux-gnu", "bpfel-unknown-unknown", "bpfeb-unknown-unknown"]
