[build]
target = "sbf-solana-solana"
rustflags = [
    "-C", "target-cpu=sbfv2",
    "-C", "target-feature=+solana,+sbf-v2",
    "-C", "link-arg=-zstack-size=32768",
    "-C", "force-frame-pointers=yes",
    "-C", "overflow-checks=yes",
    "-C", "codegen-units=1",
    "-C", "debuginfo=2",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "embed-bitcode=yes",
    "-C", "panic=abort",
    "-C", "passes=verify-sbf",
    "-C", "linker-plugin-lto=yes",
    "-C", "metadata=yes",
    "-C", "prefer-dynamic=no",
    "-C", "relocation-model=static",
    "-C", "code-model=small",
    "-C", "trap-unreachable=yes",
    "-C", "link-arg=--threads=12",
    "--cfg", "feature=\"secure-mode\"",
    "--cfg", "feature=\"post-quantum\"",
    "--cfg", "feature=\"chaos-engine\"",
    "--cfg", "solana_sbf",
    "-Z", "trap-unreachable=yes",
    "-Z", "always-encode-mir",
    "-Z", "verify-llvm-ir=yes"
]

[target.sbf-solana-solana]
linker = "solana-ldlld"
runner = "solana-sbf-runner"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = true
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false
strip = "debuginfo"

[profile.release.build-override]
opt-level = 3
codegen-units = 1
debug = true
debug-assertions = false
overflow-checks = true

[profile.release.package."*"]
opt-level = 3
codegen-units = 1
strip = "debuginfo"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
