[package]
name = "governance"
version = "0.1.0"
edition = "2021"
# Added documentation about version constraints
rust-version = "1.68.0" # Matches Solana 1.16.0 requirements

[lib]
name = "governance"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-bpf = []
# Added feature for local development and testing
local-testing = ["tokio/full", "tokio/test-util"]

[[test]]
name = "governance"
path = "tests/governance_tests.rs"
required-features = ["test-bpf"]

[[test]]
name = "chaos"
path = "tests/chaos_testing.rs"
required-features = ["test-bpf"]

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["test-bpf"]

[[test]]
name = "deployment"
path = "tests/deployment_verification.rs"
required-features = ["test-bpf"]

[dependencies]
anchor-lang = { workspace = true }
solana-program = { workspace = true }
solana-program-test = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
socket2 = { workspace = true }
solana-sdk = { workspace = true }
solana-client = "=1.16.0"
solana-account-decoder = "=1.16.0"
solana-transaction-status = "=1.16.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
chrono = "0.4"
thiserror = "1.0"
rrd = { version = "0.1", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.10"
num-derive = "0.4"
num-traits = "0.2"
spl-token = { version = "3.5", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.1", features = ["no-entrypoint"] }

[dev-dependencies]
solana-validator = "=1.16.0"
tokio-test = { workspace = true }
assert_matches = { workspace = true }
solana-sdk = { workspace = true } 