[package]
name = "glitch-worker"
version = "0.1.0"
edition = "2021"
authors = ["Glitch Gremlin Team"]
description = "Off-chain worker for Glitch Gremlin chaos testing"
license = "MIT"

[dependencies]
solana-program = "1.18.26"
spl-token = { version = "3.2.0" }
borsh = "0.10.3"
solana-sdk = "1.18.26"
hex = "0.4"
solana-client = "1.18.26"
solana-program-test = "1.18.26"
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1.0", features = ["full"] }
glitch-shared = { path = "../shared" }
[dependencies]
syscallz = { version = "0.17", features = ["linux"] }
log = "0.4"
solana-client = "1.18"
solana-program = "1.18"
solana-sdk = "1.18"
borsh = "0.10"
borsh-derive = "0.10"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
