[package]
name = "glitch-worker"
version = "0.1.0"
edition = "2021"
authors = ["Glitch Gremlin Team"]
description = "Off-chain worker for Glitch Gremlin chaos testing"
license = "MIT"

[dependencies]
solana-program = "1.18.26"
spl-token = { version = "3.2.0" }
borsh = { version = "0.10", features = ["derive"] }
hex = "0.4"
solana-client = "1.18.26"
solana-sdk = "1.18.26"
tokio = { version = "1.0", features = ["full"] }
redis = { version = "0.23.0", features = ["tokio-comp"] }
solana-client = "1.18.26"
solana-sdk = "1.18.26"
tokio = { version = "1.0", features = ["full"] }
borsh = "0.10"
hex = "0.4"
